### ISSUE TITLE
Resulting parquet files from Jenkins test are no longer deterministic

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#107]
The file sizes are no longer deterministic; not sure why.  I need to change the test suite to actually inspect the contents of the files.

**Comment by fnothaft** [comment]
Is your partition count changing? Anyways, I wouldn't expect file size to be deterministic. If records get reordered, you'll get different effective compression rates.

**Comment by laserson** [comment]
Yeah, though it's been deterministic for quite a while, and the tests just started failing a few days ago.  Either way, I'm gonna use the `python-parquet` package to inspect the contents of the files and put in place some proper tests.

**Comment by tomwhite** [comment]
This was around the time of the upgrade to Parquet 1.7.0 so perhaps something changed there. Checking the actual contents of the file sounds like an improvement anyway.

**Comment by laserson** [comment]
Closing for cleanup/refactor.
