### ISSUE TITLE
Refactor: stop using Luigi

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#109]
Too much yak shaving going on.  Focus on KISS.

**Comment by jfeala** [comment]
I've been using eggo as the infrastructure for my own Luigi + ADAM pipelines. If you drop Luigi, then I'll start a new repo for Luigi+ADAM workflows and generalize it to run anywhere. Probably will be much better that way and might be useful to others. 

(might involve borrowing/stealing some of the Luigi code from eggo, if you're ok with that)

**Comment by laserson** [comment]
Sorry for the unilateralism, @jfeala.  We decided we were just making things too complicated with Luigi (and also trying to support multiple environments).  If the direction we're going in now (Director-provisioned CDH clusters and simpler scripts for specific datasets) is also useful to you, please consider jumping on board as well.  So far it's been much simpler.  Otherwise, feel free to steal away :)

**Comment by jfeala** [comment]
No problem, I totally agree with the simpler framework. Looking forward to seeing where you go with it.

**Comment by laserson** [comment]
Closing this.
