### ISSUE TITLE
Refactor ADAM Luigi tasks to use inheritance/mixins for code reuse

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#13]
See if Luigi can correctly order/handle dags that spit out interdependent nodes in the `requires` fn.  This will make the tasks more reusable.

**Comment by tomwhite** [comment]
Has this been addressed with the recent work? If not, can you go into a bit more detail about what you think is needed?

**Comment by laserson** [comment]
Rather than using procedural logic to connect different tasks, we should see if it's convenient to use mixins that define different `run()` and `requires()` methods.  (Still half baked in my head.)

(edited the title to reflect my improved understanding of Luigi)

**Comment by tomwhite** [comment]
Thanks @laserson, that makes more sense.

**Comment by laserson** [comment]
Closing for cleanup/refactor.  No longer using Luigi.
