### ISSUE TITLE
Default parallelism set to 2 on cluster with 4 executor nodes?

### ISSUE THREAD

**Issue by NeillGibson** [bigdatagenomics/eggo#133]
Hi, 

I started a Spark / Adam cluster using the Eggo cli. 

eggo-cluster provision -n 4  
eggo-cluster config_cluster  
eggo-cluster login

I see that  the the following environment variables are exported:

cat /home/ec2-user/eggo_env_vars.sh
export EXECUTORS_PER_NODE=1
export MEMORY_PER_EXECUTOR=25662504960
export CORES_PER_EXECUTOR=4
export NUM_WORKER_NODES=4
export NODE_CORES=4
export NODE_MEMORY=32078131200
export TOTAL_EXECUTORS=4 

Up on converting a vcf file using adam-submit vcf2adam I noticed that only 2 tasks were running in parallel on just 2 of the specified 4 executor nodes. 

In the adam-shell I see that the default level of parallelism is 2. 

sc.defaultParallelism
res1: Int = 2 

Also I see that the Spark context thinks that I have just 2 executors. 

sc.getExecutorMemoryStatus
res0: scala.collection.Map[String,(Long, Long)] =
Map(
ip1 -> (278019440,278019440),
ip2 -> (555755765,555755765),
ip3 -> (555755765,555755765)) 

Also there is a mismatch between the memory specified in eggo_env_vars.sh and the memory specified by getExecutorMemoryStatus?

In the Spark configuration documentation I see that that the default level of parallelism should be 
"total number of cores on all executor nodes or 2, whichever is larger"

http://spark.apache.org/docs/latest/configuration.html

Somehow Spark is unable to detect the correct number of executors,  and the correct number of cpu per executor on the cluster started with Eggo.  

How can I make sure that Spark and Adam detect the correct number of executors and the number of cpu per executor / default parallelism level? 
Which should be 4 and 16 on a cluster started with eggo-cluster provision -n 4 ? 

Thank you,

Neill

**Comment by laserson** [comment]
Can you share the exact command line invocation of ADAM/spark-submit?

**Comment by NeillGibson** [comment]
Resolved by reading http://spark.apache.org/docs/latest/running-on-yarn.html
