### ISSUE TITLE
Upgrade Spark from 1.3 to 1.5 to make use of project Tungsten performance improvements. 

### ISSUE THREAD

**Issue by NeillGibson** [bigdatagenomics/eggo#142]
Hi, 

Could please modify the eggo cluster provision / configuration scripts to install / use a recent version of Apache Spark?

When I currently start a cluster using Eggo and start the following shells

/home/ec2-user/adam/bin/adam-shell
/opt/cloudera/parcels/CDH-5.4.8-1.cdh5.4.8.p0.4/lib/spark/bin/spark-shell

I see that the spark version is version 1.3.0 .

On the spark website I can see that there are spark releases for version 1.5.x 

https://spark.apache.org/news/spark-1-5-2-released.html 

This project Tungsten video and slides mention that a lot of performance improvements have been added in the Spark 1.4 and 1.5 versions. 
https://spark-summit.org/2015/events/deep-dive-into-project-tungsten-bringing-spark-closer-to-bare-metal/

I am currently doing some performance testing for our analytic queries and would like to make sure that I am making use of latest performance improving features. 

Thank you very much! 

Neill

**Comment by NeillGibson** [comment]
Hi, 

Currently Eggo installs cdh5.4.8. 

Cdh 5.5.0 would install with Apache Spark 5.0.
http://www.cloudera.com/content/www/en-us/documentation/enterprise/latest/topics/cdh_rn_new_in_550.html#concept_onz_f2h_mr_unique_1 

It is possible to specify somewhere which version of Cdh to install? I don't see an option for that in the Eggo CLI or code. There is no explicit reference to the Cdh version to install (5.4.8)  anywhere.

Making it possible to install Cdh 5.5.0 would enable the usage of a lot of features added to spark between 1.3 and and 1.5.

Thank you. 

Neill

**Comment by NeillGibson** [comment]
In the mean time managed to run Spark 1.5.2 as a application on YARN by following this guide. https://community.cloudera.com/t5/Advanced-Analytics-Apache-Spark/About-spark-1-5-release/td-p/31673/page/3

**Comment by heuermh** [comment]
You might be able to link to http://archive.cloudera.com/cdh5/parcels/5.5.0.8/ in your aws.conf, i.e.
https://github.com/bigdatagenomics/eggo/blob/master/eggo/resources/aws.conf#L205

**Comment by laserson** [comment]
I'm guessing this is no longer an issue, as Director should install the latest released CDH, which is 5.5.

**Comment by NeillGibson** [comment]
Ok that is good to know.

**Comment by laserson** [comment]
Also note that bc Spark can run as a yarn app, it's pretty easy to download the latest release of Spark, or build it yourself, and run it on the cluster.
