### ISSUE TITLE
Deal properly with merging and partitioning data.

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#2]
For example, the 1000 Genomes VCF data is organized into individual files by chromosome.  But this obviously causes the files to differ substantially in size.  My ideal would be to merge into a single file, or to split the genome into equal sized bins based on locus and sort the data into it.

**Comment by tomwhite** [comment]
This is being tackled in https://github.com/bigdatagenomics/eggo/issues/30 - closing.
