### ISSUE TITLE
Generate partitioned data

### ISSUE THREAD

**Issue by tomwhite** [bigdatagenomics/eggo#30]
This is called `locuspart` in the spec.

**Comment by tomwhite** [comment]
PR at https://github.com/bigdatagenomics/eggo/pull/31.

Not ready for commit yet as it depends on https://github.com/bigdatagenomics/adam/issues/651, which itself has some dependencies on Kite changes.

**Comment by tomwhite** [comment]
I updated https://github.com/bigdatagenomics/eggo/pull/33 to use a new partitioning job (from https://github.com/tomwhite/adam-partitioning; see https://github.com/bigdatagenomics/adam/issues/651 for discussion of the Spark-based one).

This is not quite ready as the number of partitions should be set based on the cluster size.

**Comment by laserson** [comment]
Closing for cleanup/refactor.  Perhaps taken care of by kite/Hive once we're on a Director cluster.
