### ISSUE TITLE
Document how to run on an arbitrary cluster

### ISSUE THREAD

**Issue by tomwhite** [bigdatagenomics/eggo#41]
It should be possible to point Eggo to run on any existing cluster. This is likely just an extension of local testing mode in terms of mechanics.

**Comment by laserson** [comment]
One eggo is refactored, there should be a pretty clear separation of code that creates/configs a cluster, vs code that executes the actual ETL steps.  My thinking now is that the "interface" will be such that the ETL code assumes some small set of ENV VARS defined and that's all.

**Comment by laserson** [comment]
Also, wrt an arbitrary cluster, we will have code that configures it to make sure all the necessary deps are installed and the env vars are set.  This will require the interface that we've been using, such as getting a "master" node host etc.

**Comment by laserson** [comment]
No longer supporting this.
