### ISSUE TITLE
S3 deadlock when generating flattened data

### ISSUE THREAD

**Issue by tomwhite** [bigdatagenomics/eggo#43]
The deadlock is the same as the one described here: https://groups.google.com/forum/#!topic/presto-users/Kouge3Jx3Ks

This is occurring since the version of Hadoop/Spark on the EC2 cluster has an old version of jets3t (0.6) - the issue is fixed in later versions. One workaround is to set the following in core-site.xml:

```
<property>
  <name>fs.s3n.impl.disable.cache</name>
  <value>true</value>
</property>
```

**Comment by laserson** [comment]
Closing for cleanup/refactor.  This will be outside eggo's responsibility for now.
