### ISSUE TITLE
Set up CI on the small test data sets for local mode

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#46]
Make sure there aren't any changes in the tools we depend on that will pull the rug out from under us.

**Comment by fnothaft** [comment]
If you've got a script you want run, let me know and I can set up a builder on @AmplabJenkins.

**Comment by tomwhite** [comment]
This would be very useful. It would be a good idea to do https://github.com/bigdatagenomics/eggo/issues/42 first so that we can test against the local filesystem and not have to worry about storing AWS credentials in Jenkins.

**Comment by laserson** [comment]
Closing for cleanup/refactor.
