### ISSUE TITLE
Tagging datasets with reference genomes

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/eggo#47]
I pulled down the 1000G genotypes for an analysis today, and lost an hour on the typical fun times  that come from mixing a GRCh37 dataset with a hg19 dataset (specifically, the 1 vs. chr1 naming mismatch). Perhaps we should "tag" input datasets with the specific reference they're aligned against, where relevant? Even further, would it be make sense to ensure that all datasets in eggo are aligned against a specific reference genome? I wouldn't want to be as restrictive as saying everything must be lifted on to hg19, but I think it might make sense to ensure that everything is aligned against a CRCh genome build instead of a UCSC build.

**Comment by laserson** [comment]
What do you think would be the best way to tag the data sets?  Put in an extra field in the json descriptor?  Also, for some reason, I was under the impression that ADAM normalizes the 1 vs chr1 issue, but I guess not.  Otherwise, I agree that doing the liftover would be insane, but I'm definitely down to prefer data sets that are all built against a GRC reference, for example.

**Comment by fnothaft** [comment]
> What do you think would be the best way to tag the data sets? Put in an extra field in the json descriptor?

That's what I was going to suggest. Best bang for the buck, IMO.

> Also, for some reason, I was under the impression that ADAM normalizes the 1 vs chr1 issue, but I guess not.

We used to have code for that in ADAM, but it was _really_ brittle so we pulled away from that. I think that referring to the MD5 for the assemblies is probably the best way, but! most file formats don't include that critical information, which is _sheer insanity_.

> Otherwise, I agree that doing the liftover would be insane, but I'm definitely down to prefer data sets that are all built against a GRC reference, for example.

Yeah. I think that's the best way to proceed, but I expect that there's enough inconsistency between projects to render this all moot. Specifically, I think 1000G, ENCODE, and TCGA use subtly different reference builds.

**Comment by laserson** [comment]
Analyze at your own risk, then?

**Comment by fnothaft** [comment]
> Analyze at your own risk, then?

Exactly.
I don't think there's a tractable way to make this "foolproof" (besides the whole keying contigs to their MD5 thing), but in a happy, future world, I'm hoping to have a provenance/workflow metadata management system that warns you "hey, you've got subtly different genome builds, are you sure you want to run several hundred hours of compute before you run into really difficult to debug issues, or do you want to fix that up front?"

**Comment by laserson** [comment]
Obviously you just go for it

**Comment by fnothaft** [comment]
@laserson The GATK agrees with you.

**Comment by laserson** [comment]
Closing for cleanup/refactor.  This is something we'll really have to deal with later if (when) eggo becomes useful/popular.
