### ISSUE TITLE
"Hardcode" the maven version into "install_maven"

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#60]
This should be an implementation detail.  The user shouldn't really need to specify this in the eggo config.

**Comment by tomwhite** [comment]
I think we should move away from building ADAM on the cluster (see https://github.com/bigdatagenomics/eggo/pull/52), so this would go away.

**Comment by laserson** [comment]
That would be ideal, but i'm just worried that we're gonna be co-developing ADAM to address problems we'll find here.  Perhaps we can just make it configurable.  There is a way to specify a release, or you can specify the fork/branch, and in the latter case, it just pulls the package rather than building it.

**Comment by tomwhite** [comment]
If we can support both without too much trouble then that's fine.

**Comment by laserson** [comment]
Closing for cleanup/refactor.
